//! Error codes.
//!
//! # References
//! - <https://kafka.apache.org/protocol#protocol_error_codes>

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(clippy::enum_variant_names)]
#[non_exhaustive]
pub enum Error {
    UnknownServerError,
    OffsetOutOfRange,
    CorruptMessage,
    UnknownTopicOrPartition,
    InvalidFetchSize,
    LeaderNotAvailable,
    NotLeaderOrFollower,
    RequestTimedOut,
    BrokerNotAvailable,
    ReplicaNotAvailable,
    MessageTooLarge,
    StaleControllerEpoch,
    OffsetMetadataTooLarge,
    NetworkException,
    CoordinatorLoadInProgress,
    CoordinatorNotAvailable,
    NotCoordinator,
    InvalidTopicException,
    RecordListTooLarge,
    NotEnoughReplicas,
    NotEnoughReplicasAfterAppend,
    InvalidRequiredAcks,
    IllegalGeneration,
    InconsistentGroupProtocol,
    InvalidGroupId,
    UnknownMemberId,
    InvalidSessionTimeout,
    RebalanceInProgress,
    InvalidCommitOffsetSize,
    TopicAuthorizationFailed,
    GroupAuthorizationFailed,
    ClusterAuthorizationFailed,
    InvalidTimestamp,
    UnsupportedSaslMechanism,
    IllegalSaslState,
    UnsupportedVersion,
    TopicAlreadyExists,
    InvalidPartitions,
    InvalidReplicationFactor,
    InvalidReplicaAssignment,
    InvalidConfig,
    NotController,
    InvalidRequest,
    UnsupportedForMessageFormat,
    PolicyViolation,
    OutOfOrderSequenceNumber,
    DuplicateSequenceNumber,
    InvalidProducerEpoch,
    InvalidTxnState,
    InvalidProducerIdMapping,
    InvalidTransactionTimeout,
    ConcurrentTransactions,
    TransactionCoordinatorFenced,
    TransactionalIdAuthorizationFailed,
    SecurityDisabled,
    OperationNotAttempted,
    KafkaStorageError,
    LogDirNotFound,
    SaslAuthenticationFailed,
    UnknownProducerId,
    ReassignmentInProgress,
    DelegationTokenAuthDisabled,
    DelegationTokenNotFound,
    DelegationTokenOwnerMismatch,
    DelegationTokenRequestNotAllowed,
    DelegationTokenAuthorizationFailed,
    DelegationTokenExpired,
    InvalidPrincipalType,
    NonEmptyGroup,
    GroupIdNotFound,
    FetchSessionIdNotFound,
    InvalidFetchSessionEpoch,
    ListenerNotFound,
    TopicDeletionDisabled,
    FencedLeaderEpoch,
    UnknownLeaderEpoch,
    UnsupportedCompressionType,
    StaleBrokerEpoch,
    OffsetNotAvailable,
    MemberIdRequired,
    PreferredLeaderNotAvailable,
    GroupMaxSizeReached,
    FencedInstanceId,
    EligibleLeadersNotAvailable,
    ElectionNotNeeded,
    NoReassignmentInProgress,
    GroupSubscribedToTopic,
    InvalidRecord,
    UnstableOffsetCommit,
    ThrottlingQuotaExceeded,
    ProducerFenced,
    ResourceNotFound,
    DuplicateResource,
    UnacceptableCredential,
    InconsistentVoterSet,
    InvalidUpdateVersion,
    FeatureUpdateFailed,
    PrincipalDeserializationFailure,
    SnapshotNotFound,
    PositionOutOfRange,
    UnknownTopicId,
    DuplicateBrokerRegistration,
    BrokerIdNotRegistered,
    InconsistentTopicId,
    InconsistentClusterId,
    TransactionalIdNotFound,
    Unknown(i16),
}

impl Error {
    /// Conversion from [`i16`].
    ///
    /// This cannot be a `From` trait due to <https://github.com/rust-lang/rfcs/issues/1402>.
    pub fn new(code: i16) -> Option<Self> {
        match code {
            -1 => Some(Self::UnknownServerError),
            0 => None,
            1 => Some(Self::OffsetOutOfRange),
            2 => Some(Self::CorruptMessage),
            3 => Some(Self::UnknownTopicOrPartition),
            4 => Some(Self::InvalidFetchSize),
            5 => Some(Self::LeaderNotAvailable),
            6 => Some(Self::NotLeaderOrFollower),
            7 => Some(Self::RequestTimedOut),
            8 => Some(Self::BrokerNotAvailable),
            9 => Some(Self::ReplicaNotAvailable),
            10 => Some(Self::MessageTooLarge),
            11 => Some(Self::StaleControllerEpoch),
            12 => Some(Self::OffsetMetadataTooLarge),
            13 => Some(Self::NetworkException),
            14 => Some(Self::CoordinatorLoadInProgress),
            15 => Some(Self::CoordinatorNotAvailable),
            16 => Some(Self::NotCoordinator),
            17 => Some(Self::InvalidTopicException),
            18 => Some(Self::RecordListTooLarge),
            19 => Some(Self::NotEnoughReplicas),
            20 => Some(Self::NotEnoughReplicasAfterAppend),
            21 => Some(Self::InvalidRequiredAcks),
            22 => Some(Self::IllegalGeneration),
            23 => Some(Self::InconsistentGroupProtocol),
            24 => Some(Self::InvalidGroupId),
            25 => Some(Self::UnknownMemberId),
            26 => Some(Self::InvalidSessionTimeout),
            27 => Some(Self::RebalanceInProgress),
            28 => Some(Self::InvalidCommitOffsetSize),
            29 => Some(Self::TopicAuthorizationFailed),
            30 => Some(Self::GroupAuthorizationFailed),
            31 => Some(Self::ClusterAuthorizationFailed),
            32 => Some(Self::InvalidTimestamp),
            33 => Some(Self::UnsupportedSaslMechanism),
            34 => Some(Self::IllegalSaslState),
            35 => Some(Self::UnsupportedVersion),
            36 => Some(Self::TopicAlreadyExists),
            37 => Some(Self::InvalidPartitions),
            38 => Some(Self::InvalidReplicationFactor),
            39 => Some(Self::InvalidReplicaAssignment),
            40 => Some(Self::InvalidConfig),
            41 => Some(Self::NotController),
            42 => Some(Self::InvalidRequest),
            43 => Some(Self::UnsupportedForMessageFormat),
            44 => Some(Self::PolicyViolation),
            45 => Some(Self::OutOfOrderSequenceNumber),
            46 => Some(Self::DuplicateSequenceNumber),
            47 => Some(Self::InvalidProducerEpoch),
            48 => Some(Self::InvalidTxnState),
            49 => Some(Self::InvalidProducerIdMapping),
            50 => Some(Self::InvalidTransactionTimeout),
            51 => Some(Self::ConcurrentTransactions),
            52 => Some(Self::TransactionCoordinatorFenced),
            53 => Some(Self::TransactionalIdAuthorizationFailed),
            54 => Some(Self::SecurityDisabled),
            55 => Some(Self::OperationNotAttempted),
            56 => Some(Self::KafkaStorageError),
            57 => Some(Self::LogDirNotFound),
            58 => Some(Self::SaslAuthenticationFailed),
            59 => Some(Self::UnknownProducerId),
            60 => Some(Self::ReassignmentInProgress),
            61 => Some(Self::DelegationTokenAuthDisabled),
            62 => Some(Self::DelegationTokenNotFound),
            63 => Some(Self::DelegationTokenOwnerMismatch),
            64 => Some(Self::DelegationTokenRequestNotAllowed),
            65 => Some(Self::DelegationTokenAuthorizationFailed),
            66 => Some(Self::DelegationTokenExpired),
            67 => Some(Self::InvalidPrincipalType),
            68 => Some(Self::NonEmptyGroup),
            69 => Some(Self::GroupIdNotFound),
            70 => Some(Self::FetchSessionIdNotFound),
            71 => Some(Self::InvalidFetchSessionEpoch),
            72 => Some(Self::ListenerNotFound),
            73 => Some(Self::TopicDeletionDisabled),
            74 => Some(Self::FencedLeaderEpoch),
            75 => Some(Self::UnknownLeaderEpoch),
            76 => Some(Self::UnsupportedCompressionType),
            77 => Some(Self::StaleBrokerEpoch),
            78 => Some(Self::OffsetNotAvailable),
            79 => Some(Self::MemberIdRequired),
            80 => Some(Self::PreferredLeaderNotAvailable),
            81 => Some(Self::GroupMaxSizeReached),
            82 => Some(Self::FencedInstanceId),
            83 => Some(Self::EligibleLeadersNotAvailable),
            84 => Some(Self::ElectionNotNeeded),
            85 => Some(Self::NoReassignmentInProgress),
            86 => Some(Self::GroupSubscribedToTopic),
            87 => Some(Self::InvalidRecord),
            88 => Some(Self::UnstableOffsetCommit),
            89 => Some(Self::ThrottlingQuotaExceeded),
            90 => Some(Self::ProducerFenced),
            91 => Some(Self::ResourceNotFound),
            92 => Some(Self::DuplicateResource),
            93 => Some(Self::UnacceptableCredential),
            94 => Some(Self::InconsistentVoterSet),
            95 => Some(Self::InvalidUpdateVersion),
            96 => Some(Self::FeatureUpdateFailed),
            97 => Some(Self::PrincipalDeserializationFailure),
            98 => Some(Self::SnapshotNotFound),
            99 => Some(Self::PositionOutOfRange),
            100 => Some(Self::UnknownTopicId),
            101 => Some(Self::DuplicateBrokerRegistration),
            102 => Some(Self::BrokerIdNotRegistered),
            103 => Some(Self::InconsistentTopicId),
            104 => Some(Self::InconsistentClusterId),
            105 => Some(Self::TransactionalIdNotFound),
            _ => Some(Self::Unknown(code)),
        }
    }

    pub fn code(&self) -> i16 {
        match self {
            Error::UnknownServerError => -1,
            Error::OffsetOutOfRange => 1,
            Error::CorruptMessage => 2,
            Error::UnknownTopicOrPartition => 3,
            Error::InvalidFetchSize => 4,
            Error::LeaderNotAvailable => 5,
            Error::NotLeaderOrFollower => 6,
            Error::RequestTimedOut => 7,
            Error::BrokerNotAvailable => 8,
            Error::ReplicaNotAvailable => 9,
            Error::MessageTooLarge => 10,
            Error::StaleControllerEpoch => 11,
            Error::OffsetMetadataTooLarge => 12,
            Error::NetworkException => 13,
            Error::CoordinatorLoadInProgress => 14,
            Error::CoordinatorNotAvailable => 15,
            Error::NotCoordinator => 16,
            Error::InvalidTopicException => 17,
            Error::RecordListTooLarge => 18,
            Error::NotEnoughReplicas => 19,
            Error::NotEnoughReplicasAfterAppend => 20,
            Error::InvalidRequiredAcks => 21,
            Error::IllegalGeneration => 22,
            Error::InconsistentGroupProtocol => 23,
            Error::InvalidGroupId => 24,
            Error::UnknownMemberId => 25,
            Error::InvalidSessionTimeout => 26,
            Error::RebalanceInProgress => 27,
            Error::InvalidCommitOffsetSize => 28,
            Error::TopicAuthorizationFailed => 29,
            Error::GroupAuthorizationFailed => 30,
            Error::ClusterAuthorizationFailed => 31,
            Error::InvalidTimestamp => 32,
            Error::UnsupportedSaslMechanism => 33,
            Error::IllegalSaslState => 34,
            Error::UnsupportedVersion => 35,
            Error::TopicAlreadyExists => 36,
            Error::InvalidPartitions => 37,
            Error::InvalidReplicationFactor => 38,
            Error::InvalidReplicaAssignment => 39,
            Error::InvalidConfig => 40,
            Error::NotController => 41,
            Error::InvalidRequest => 42,
            Error::UnsupportedForMessageFormat => 43,
            Error::PolicyViolation => 44,
            Error::OutOfOrderSequenceNumber => 45,
            Error::DuplicateSequenceNumber => 46,
            Error::InvalidProducerEpoch => 47,
            Error::InvalidTxnState => 48,
            Error::InvalidProducerIdMapping => 49,
            Error::InvalidTransactionTimeout => 50,
            Error::ConcurrentTransactions => 51,
            Error::TransactionCoordinatorFenced => 52,
            Error::TransactionalIdAuthorizationFailed => 53,
            Error::SecurityDisabled => 54,
            Error::OperationNotAttempted => 55,
            Error::KafkaStorageError => 56,
            Error::LogDirNotFound => 57,
            Error::SaslAuthenticationFailed => 58,
            Error::UnknownProducerId => 59,
            Error::ReassignmentInProgress => 60,
            Error::DelegationTokenAuthDisabled => 61,
            Error::DelegationTokenNotFound => 62,
            Error::DelegationTokenOwnerMismatch => 63,
            Error::DelegationTokenRequestNotAllowed => 64,
            Error::DelegationTokenAuthorizationFailed => 65,
            Error::DelegationTokenExpired => 66,
            Error::InvalidPrincipalType => 67,
            Error::NonEmptyGroup => 68,
            Error::GroupIdNotFound => 69,
            Error::FetchSessionIdNotFound => 70,
            Error::InvalidFetchSessionEpoch => 71,
            Error::ListenerNotFound => 72,
            Error::TopicDeletionDisabled => 73,
            Error::FencedLeaderEpoch => 74,
            Error::UnknownLeaderEpoch => 75,
            Error::UnsupportedCompressionType => 76,
            Error::StaleBrokerEpoch => 77,
            Error::OffsetNotAvailable => 78,
            Error::MemberIdRequired => 79,
            Error::PreferredLeaderNotAvailable => 80,
            Error::GroupMaxSizeReached => 81,
            Error::FencedInstanceId => 82,
            Error::EligibleLeadersNotAvailable => 83,
            Error::ElectionNotNeeded => 84,
            Error::NoReassignmentInProgress => 85,
            Error::GroupSubscribedToTopic => 86,
            Error::InvalidRecord => 87,
            Error::UnstableOffsetCommit => 88,
            Error::ThrottlingQuotaExceeded => 89,
            Error::ProducerFenced => 90,
            Error::ResourceNotFound => 91,
            Error::DuplicateResource => 92,
            Error::UnacceptableCredential => 93,
            Error::InconsistentVoterSet => 94,
            Error::InvalidUpdateVersion => 95,
            Error::FeatureUpdateFailed => 96,
            Error::PrincipalDeserializationFailure => 97,
            Error::SnapshotNotFound => 98,
            Error::PositionOutOfRange => 99,
            Error::UnknownTopicId => 100,
            Error::DuplicateBrokerRegistration => 101,
            Error::BrokerIdNotRegistered => 102,
            Error::InconsistentTopicId => 103,
            Error::InconsistentClusterId => 104,
            Error::TransactionalIdNotFound => 105,
            Error::Unknown(code) => *code,
        }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::error::Error for Error {}
